### ISSUE TITLE
undefined method `receive' for nil:NilClass

### ISSUE THREAD

**Issue by guyzmo** [pusher-community/pusher-websocket-ruby#51]
there's an issue that looks related to your library that's being reported on travis-ci/travis.rb#476. It doesn't look like it's been reported here, so here am I posting the traceback:

```
    NoMethodError: undefined method `receive' for nil:NilClass
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/listener.rb:123:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/methods.rb:90:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/artifact.rb:54:in `body'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

it's consistently happening each time one runs a `travis logs` while a build is in progress.

**Comment by glensc** [comment]
perhaps #46 fixes all this?
